-- HUELLA - esquema Supabase vigente
-- Este archivo evita mantener una copia desactualizada e insegura del esquema.
-- Ejecutar la migracion:
-- supabase/migrations/20260708_iteration_1_supabase.sql
