"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Edit } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DetailSkeleton, FriendlyError } from "@/components/feedback";
import { listMyCases } from "@/lib/cases";
import { listMyRegisteredPets, type RegisteredPet } from "@/lib/sprint14-store";
import { friendlyError } from "@/lib/form-validation";
export default function RegisteredPetDetailPage(){const{id}=useParams<{id:string}>();const[pet,setPet]=useState<RegisteredPet|null>(null),[caseId,setCaseId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{Promise.all([listMyRegisteredPets(),listMyCases()]).then(([pets,cases])=>{setPet(pets.find((item)=>item.id===id)??null);setCaseId(cases.find((item)=>item.petId===id&&item.status!=="reunido"&&item.status!=="archivado")?.id??"");}).catch((caught)=>setError(friendlyError(caught,"No se pudo cargar la mascota."))).finally(()=>setLoading(false));},[id]);if(loading)return <DetailSkeleton/>;if(!pet)return <main className="container py-10"><FriendlyError message={error||"No se encontró esta mascota."}/></main>;const photos=Array.from(new Set([...(pet.fotos??[]),pet.foto_principal,pet.foto_url].filter((url):url is string=>Boolean(url)))).slice(0,3);return <main className="container py-6"><Link href="/mis-mascotas" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#6B6860]"><ArrowLeft size={17}/>Volver a Mis mascotas</Link><section className="form-card mx-auto max-w-3xl space-y-5"><div className="flex flex-col gap-3 min-[390px]:flex-row min-[390px]:justify-between"><div><h1 className="font-serif text-4xl">{pet.nombre}</h1><p className="text-sm text-[#6B6860]">Ficha preventiva</p></div><span className={`status-pill ${caseId?"status-perdido":"status-reunido"}`}>{caseId?"Búsqueda activa":"Sin búsqueda activa"}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{photos.map((url,index)=><img key={url} src={url} alt={`${pet.nombre}, fotografía ${index+1}`} className="h-52 w-full rounded-xl bg-[#F8F7F4] object-contain"/>)}</div><dl className="grid gap-3 text-sm min-[390px]:grid-cols-2"><div><dt className="font-bold">Especie</dt><dd>{pet.especie||"No indicada"}</dd></div><div><dt className="font-bold">Raza</dt><dd>{pet.raza||"No indicada"}</dd></div><div><dt className="font-bold">Sexo</dt><dd>{pet.sexo||"No indicado"}</dd></div><div><dt className="font-bold">Edad</dt><dd>{pet.edad||"No indicada"}</dd></div><div><dt className="font-bold">Color</dt><dd>{pet.color||"No indicado"}</dd></div><div><dt className="font-bold">Salud</dt><dd>{pet.salud||"Sin información"}</dd></div></dl><div><h2 className="font-bold">Descripción</h2><p className="mt-1 text-sm leading-6 text-[#6B6860]">{pet.caracteristicas_personalizadas||"Sin descripción."}</p></div><div className="grid gap-2 min-[390px]:grid-cols-2"><Button variant="outline" asChild><Link href={`/mis-mascotas/${pet.id}/editar`}><Edit size={18}/>Editar mascota</Link></Button>{caseId?<Button asChild><Link href={`/pet/${caseId}`}>Ver centro de búsqueda</Link></Button>:<Button asChild><Link href={`/perdi-mi-mascota?petId=${pet.id}`}>Reportar pérdida</Link></Button>}</div></section></main>;}
