export type PetStatus = "perdido" | "encontrado" | "reunido";

export type Pet = {
  id: string;
  nombre: string;
  tipo: string;
  raza: string;
  descripcion: string;
  estado: PetStatus;
  distrito: string;
  direccion: string;
  latitud: number;
  longitud: number;
  whatsapp: string;
  foto_principal: string;
  fecha_reporte: string;
  creado_en: string;
  recompensa_ofrecida?: boolean;
  recompensa_monto?: number | null;
  recompensa_texto?: string | null;
  fotos?: string[];
  caracteristicas?: string[];
  caracteristicas_personalizadas?: string;
  condiciones_especiales?: string[];
  alias?: string[];
  edad?: string | null;
  salud?: string | null;
  esterilizado?: boolean | null;
  observaciones?: string | null;
  cerrado_en?: string | null;
  owner_token?: string | null;
};

export type Sighting = {
  id: string;
  pet_id: string | null;
  report_id?: string | null;
  especie?: string | null;
  tamano?: string | null;
  color?: string | null;
  distrito?: string | null;
  comentario: string;
  foto: string | null;
  fotos?: string[];
  latitud: number | null;
  longitud: number | null;
  ubicacion?: string | null;
  estado?: "pendiente" | "confirmado" | "descartado";
  estado_avistamiento?: "pendiente" | "confirmado" | "descartado";
  estado_revision?: "por_revisar" | "posible_coincidencia" | "descartado" | "alerta_falsa" | "informacion_enganosa" | "encontrada";
  situacion?: "solo_la_vi" | "sigue_en_la_zona" | "la_tengo_conmigo" | "veterinaria" | "refugio" | "herida" | "siguiendo";
  llevaba_placa?: "si" | "no" | "no_pude_verificar";
  nombre_observado?: string | null;
  feedback_reportero?: string | null;
  visto_en?: string;
  owner_token?: string | null;
  reporter_name?: string | null;
  reporter_phone?: string | null;
  reporter_is_anonymous?: boolean;
  creado_en: string;
};

export type Notification = {
  id: string;
  pet_id: string;
  tipo: "nuevo_avistamiento" | "avistamiento_confirmado" | "reporte_actualizado" | "reporte_cerrado" | "coincidencia_alta" | "caso_cercano";
  mensaje: string;
  leido: boolean;
  creado_en: string;
};
